version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "20:56"
    groups:
      all-actions:
        patterns: [ "*" ]
    ignore:
      - dependency-name: "ubuntu"
        versions: [">= 23.00"]
  - package-ecosystem: "docker"
    directories: 
      - "/dockerfiles/antlr"
      - "/dockerfiles/base"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "20:56"
    groups:
      all-images:
        patterns: [ "*" ]
