version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "20:56"
    cooldown:
      default-days: 5
    groups:
      actions:
        applies-to: "version-updates"
        patterns: [ "*" ]
  - package-ecosystem: "docker"
    directories:
      - "/contexts/antlr"
      - "/contexts/base"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "20:56"
    cooldown:
      default-days: 5
    groups:
      images:
        applies-to: "version-updates"
        patterns: [ "*" ]
