FROM ghcr.io/dentist8204/images/base:latest

RUN apk add --no-cache texlive texlive-latexrecommended texlive-latexextra texlive-pictures

LABEL org.opencontainers.image.description="Alpine image with texlive installed"
