name: All

on:
  workflow_dispatch:
  schedule:
    - cron: '47 7 * * *'

jobs:
  base:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "base"
  derivatives:
    needs: base
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image_name:
          - "age"
          - "latex"
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: ${{ matrix.image_name }}
  antlr:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "antlr"
    
