name: All

on:
  workflow_dispatch:
  pull_request:
    types:
     - opened
     - reopened
     - synchronize
    paths-ignore:
     - LICENSE
     - README.md

jobs:
  base:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "base"
  derivatives:
    needs: base
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image_name:
          - "age"
          - "latex"
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: ${{ matrix.image_name }}
  antlr:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "antlr"
  make-seccomp-profiles:
    needs:
     - antlr
     - derivatives
    permissions:
      actions: write
    strategy:
      matrix:
        image_name:
          - "age"
          - "antlr"
          - "latex"
    uses: ./.github/workflows/make-seccomp-profile.yml
    with:
      image_name: ${{ matrix.image_name }}
    
