name: All

on:
  workflow_dispatch:
  schedule:
    - cron: '39 12 * * *'

jobs:
  base:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "base"
  derivatives:
    needs: base
    strategy:
      matrix:
        image_name:
          - "age"
          - "latex"
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: ${{ matrix.image_name }}
  antlr:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "antlr"
    
