name: Build and Push All Images

on:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        default: false
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false

concurrency:
  group: build-and-push-all-images-${{ github.event_name }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  base:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "base"
      push: ${{ inputs.push }}

  derivatives:
    needs: base
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        image_name:
          - "age"
          - "latex"
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: ${{ matrix.image_name }}
      push: ${{ inputs.push }}

  antlr:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: "antlr"
      push: ${{ inputs.push }}
