name: Build

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: sigstore/cosign-installer@v4.1.2
    - uses: actions/checkout@v6
    - name: Build base
      run: docker build . --file base.Dockerfile --tag base
    - name: Build age
      run: docker build . --file age.Dockerfile --tag ${{ env.REGISTRY }}/${{ env.REPO }}/age --pull=false
    - name: Build latex
      run: docker build . --file latex.Dockerfile --tag ${{ env.REGISTRY }}/${{ env.REPO }}/latex --pull=false
    - uses: docker/login-action@v4
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push age
      run: docker push ${{ env.REGISTRY }}/${{ env.REPO }}/age
    - name: Push latex
      run: docker push ${{ env.REGISTRY }}/${{ env.REPO }}/latex
    - name: Sign age
      run: cosign sign --oidc --yes ${{ env.REGISTRY }}/${{ env.REPO }}/age
    - name: Sign latex
      run: cosign sign --oidc --yes ${{ env.REGISTRY }}/${{ env.REPO }}/latex
    
    
