name: Build and Push

on:
  workflow_dispatch:
  schedule:
    - cron: '39 12 * * *'

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
      with:
        version: v0.34.1
    - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
      id: build-and-push
      with:
        context: .
        file: base.Dockerfile
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/base:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.source=https://github.com/dentist8204/images
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.description=Arch image with an unprivileged user
    - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6
      with:
        cosign-release: 'v3.0.6'
    - name: Sign image
      run: cosign sign --yes ${{ env.REGISTRY }}/${{ github.repository }}/base@${{ steps.build-and-push.outputs.digest }}
      
  derivatives:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      matrix:
        name:
          - age
          - latex
          - ssh
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
      with:
        version: v0.34.1
    - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
      id: build-and-push
      with:
        context: .
        file: ${{ matrix.name }}.Dockerfile
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.source=https://github.com/dentist8204/images
          org.opencontainers.image.licenses=MIT
    - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6
      with:
        cosign-release: 'v3.0.6'
    - name: Sign image
      run: cosign sign --yes ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}@${{ steps.build-and-push.outputs.digest }}
    
    
