name: Build

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        name:
          - age
          - latex
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Build base
      run: docker build . --file base.Dockerfile --tag base
    - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}
    - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
      id: build-and-push
      with:
        context: .
        file: ${{ matrix.name }}.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6
      with:
        cosign-release: 'v3.0.6'
    - name: Sign image
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
    
    
