name: Check Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-paths:
    runs-on: ubuntu-26.04
    outputs:
      build: ${{ steps.filter.outputs.build }}
      audit: ${{ steps.filter.outputs.audit }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            build:
              - '.github/workflows/build/**'
              - 'contexts/**'
            audit:
              - '.github/workflows/audit/**'
              - 'config/seccomp/**'
              - 'environments/**'
              - 'scripts/seccomp/**'

  build:
    needs: check-paths
    if: ${{ needs.check-paths.outputs.build }} == 'true'
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/build/all.yml

  audit:
    needs:
      - check-paths
      - build
    if: ${{ needs.check-paths.outputs.audit }} == 'true' && (${{ needs.build.result }} == 'success' || ${{ needs.build.result }} == 'skipped')
    permissions:
      actions: write
    uses: ./.github/workflows/audit/all.yml

  finish:
    runs-on: ubuntu-26.04
    needs:
      - build
      - audit
    if: (${{ needs.audit.result }} == 'success' || ${{ needs.audit.result }} == 'skipped') && (${{ needs.build.result }} == 'success' || ${{ needs.build.result }} == 'skipped')
    steps:
      - run: true
    
