name: Make Seccomp Profile

on:
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: choice
        options: ["age", "antlr", "base", "latex"]
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  list-syscalls:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends auditd bpftrace crun
    - run: |
        set -euo pipefail
        sudo bpftrace -e '
          /* defined in kernel/auditsc.c */
          kprobe:audit_seccomp
          { 
            /* SECCOMP_RET_LOG defined in include/uapi/linux/seccomp.h */
            if (arg2 == 0x7ffc0000) {
              @[arg0] = 1; 
            }
          }
        ' -o syscalls.txt &
        
        BPF_PID=$!
        sleep 5
        CONTAINER_ID=$(docker create --runtime=crun --security-opt=seccomp=config/default-docker-log-seccomp.json ghcr.io/${{ github.repository }}/${{ inputs.image_name }}:latest uname -a)
        docker start $CONTAINER_ID
        timeout 20s docker wait $CONTAINER_ID
        sudo kill $BPF_PID
    - run: |
        set -euo pipefail
        cat <<EOF > seccomp-profile.json
        {
          "defaultAction": "SCMP_ACT_ERRNO",
          "defaultErrno":"ENOSYS",
          "architectures": [
            "SCMP_ARCH_X86_64"
          ],
          "syscalls": [
            {
              "action": "SCMP_ACT_ALLOW",
              "names": [
        EOF
        
        sed -nE 's/.*@\[([0-9]+)\].*/\1/p' syscalls.txt | xargs -I {} sh -c "ausyscall {}" | sort |
        sed 's/^/        "/;s/$/",/' |  sed '$ s/,$//' >> seccomp-profile.json
        
        cat <<EOF >> seccomp-profile.json
              ]
            }
          ]
        }
        EOF
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: seccomp-${{ inputs.image_name }}
        path: |
          syscalls.txt
          seccomp-profile.json
      
      
