name: Make Seccomp Profile

on:
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: choice
        options: ["age", "antlr", "base", "latex"]
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  make-seccomp-profile:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends bpftrace
    - run: |
        CONTAINER_ID=$(docker create ghcr.io/${{ github.repository }}/${{ inputs.image_name }}:latest uname -a)
        CGROUP_ID=$(sudo cat /sys/fs/cgroup/system.slice/docker-${CONTAINER_ID}.scope/cgroup.id)
        sudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter /cgroup == $1/ { @[probe("syscall_name")] = 1; }' $CGROUP_ID -o syscalls.txt &
        BPF_PID=$!
        docker start $CONTAINER_ID
        timeout 20s docker wait $CONTAINER_ID
        sudo kill $BPF_PID
    - run: |
        echo '{"defaultAction":"SCMP_ACT_ERRNO","defaultErrno":"ENOSYS","architectures":["SCMP_ARCH_X86_64"],"syscalls":[{"action":"SCMP_ACT_ALLOW","names":[' > seccomp-profile.json
        sed -E 's/.*\[([^\]]+)\].*/"\1",/' syscalls.txt | sed '$ s/,$//' >> seccomp-profile.json
        echo ']}]}' >> seccomp-profile.json
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: seccomp-profile-${{ inputs.image_name }}
        path: seccomp-profile-${{ inputs.image_name }}.json
      
      
